import React, { useState, useEffect } from 'react';
import { RiskAlert, AlertSeverity, AlertStatus } from '@/types';
import { MockBackend } from '@/services/mockBackend';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  doctorId: string;
}

export const NotificationCenter: React.FC<Props> = ({ doctorId }) => {
  const [alerts, setAlerts] = useState<RiskAlert[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [unreadCount, setUnreadCount] = useState(0);

  const fetchAlerts = async () => {
    const data = await MockBackend.getAlerts(doctorId);
    setAlerts(data);
    setUnreadCount(data.filter(a => a.status === AlertStatus.NEW).length);
  };

  useEffect(() => {
    fetchAlerts();
    // Subscribe to event bus to receive alerts generated by background simulation
    const unsubscribe = MockBackend.subscribe(fetchAlerts);
    return () => unsubscribe();
  }, [doctorId]);

  const handleAcknowledge = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    await MockBackend.updateAlertStatus(id, AlertStatus.ACKNOWLEDGED);
    fetchAlerts();
  };

  const handleResolve = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    await MockBackend.updateAlertStatus(id, AlertStatus.RESOLVED);
    fetchAlerts();
  };

  const getSeverityColor = (severity: AlertSeverity) => {
    switch (severity) {
      case AlertSeverity.CRITICAL: return 'bg-red-50 border-red-200 text-red-800';
      case AlertSeverity.HIGH: return 'bg-orange-50 border-orange-200 text-orange-800';
      case AlertSeverity.MEDIUM: return 'bg-yellow-50 border-yellow-200 text-yellow-800';
      default: return 'bg-slate-50 border-slate-200 text-slate-800';
    }
  };

  return (
    <div className="relative z-50">
      {/* Bell Icon */}
      <button 
        onClick={() => setIsOpen(!isOpen)} 
        className="relative p-2 text-slate-400 hover:text-slate-600 transition-colors rounded-full hover:bg-slate-100"
      >
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
        {unreadCount > 0 && (
          <span className="absolute top-1 right-1 flex h-4 w-4">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-4 w-4 bg-red-500 text-[10px] text-white justify-center items-center">{unreadCount}</span>
          </span>
        )}
      </button>

      {/* Dropdown Panel */}
      <AnimatePresence>
        {isOpen && (
          <>
            <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
            <motion.div 
              initial={{ opacity: 0, y: 10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 10, scale: 0.95 }}
              className="absolute right-0 mt-2 w-96 bg-white rounded-xl shadow-xl border border-slate-100 z-50 overflow-hidden"
            >
              <div className="p-4 border-b border-slate-50 bg-slate-50/50 flex justify-between items-center">
                <h3 className="font-bold text-slate-700">Risk Alerts</h3>
                <span className="text-xs font-medium text-slate-500">{alerts.length} Active</span>
              </div>
              
              <div className="max-h-[400px] overflow-y-auto custom-scrollbar">
                {alerts.length === 0 ? (
                   <div className="p-8 text-center text-slate-400 text-sm">No active alerts.</div>
                ) : (
                  alerts.map(alert => (
                    <div 
                      key={alert.id} 
                      className={`p-4 border-b border-slate-50 hover:bg-slate-50 transition-colors relative ${alert.status === AlertStatus.NEW ? 'bg-blue-50/30' : ''}`}
                    >
                      {alert.status === AlertStatus.NEW && (
                        <div className="absolute left-0 top-0 bottom-0 w-1 bg-blue-500"></div>
                      )}
                      <div className="flex justify-between items-start mb-1">
                        <span className="font-bold text-slate-800 text-sm">{alert.patientName}</span>
                        <span className="text-xs text-slate-400">{new Date(alert.timestamp).toLocaleTimeString()}</span>
                      </div>
                      
                      <div className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[10px] font-bold uppercase mb-2 ${getSeverityColor(alert.severity)}`}>
                        {alert.severity === AlertSeverity.CRITICAL && <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse"></span>}
                        {alert.severity} RISK ({alert.riskScore}/100)
                      </div>
                      
                      <p className="text-xs text-slate-600 mb-2">{alert.message}</p>
                      
                      <div className="flex flex-wrap gap-1 mb-3">
                        {alert.keyFactors.map((factor, i) => (
                          <span key={i} className="text-[10px] bg-white border border-slate-200 px-1.5 py-0.5 rounded text-slate-500">{factor}</span>
                        ))}
                      </div>

                      <div className="flex gap-2 justify-end">
                        {alert.status === AlertStatus.NEW && (
                          <button onClick={(e) => handleAcknowledge(alert.id, e)} className="text-xs font-medium text-blue-600 hover:text-blue-800 hover:bg-blue-50 px-2 py-1 rounded transition-colors">
                            Acknowledge
                          </button>
                        )}
                        <button onClick={(e) => handleResolve(alert.id, e)} className="text-xs font-medium text-teal-600 hover:text-teal-800 hover:bg-teal-50 px-2 py-1 rounded transition-colors">
                          Resolve
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};